"use client";
import {useState,useEffect,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Skeleton} from '@/components/ui/skeleton';
import {Progress} from '@/components/ui/progress';
import {Flame,Trophy,Zap,ChevronLeft,ChevronRight,RefreshCw,Check,Settings2,ArrowUpRight} from 'lucide-react';
import {type Day,dayKey,shiftDay,calendar,streak,dailyTier} from '@/lib/activity';
const fmt=(n:number)=>n.toLocaleString('ja-JP');
const wd=['日','月','火','水','木','金','土'];
const short=(d:string)=>`${Number(d.slice(5,7))}/${Number(d.slice(8))}`;
export default function Home(){
 const [name,setName]=useState('gakkii415'),[active,setActive]=useState(''),[days,setDays]=useState<Day[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[settings,setSettings]=useState(false),[goal,setGoal]=useState(10),[goalInput,setGoalInput]=useState('10'),[today,setToday]=useState(''),[selected,setSelected]=useState(''),[offset,setOffset]=useState(0),[updated,setUpdated]=useState('');const request=useRef(0);
 async function load(u:string){const id=++request.current;setBusy(true);setError('');try{const r=await fetch('/api/contributions?user='+encodeURIComponent(u),{signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw Error(d.error);if(id!==request.current)return;setDays(d.contributions);setActive(u);setUpdated(new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}));setSettings(false);try{localStorage.setItem('github-counts-user',u)}catch{}}catch(e){if(id===request.current)setError(e instanceof Error?e.message:'取得できませんでした。')}finally{if(id===request.current)setBusy(false)}}
 useEffect(()=>{const t=dayKey(new Date());setToday(t);setSelected(t);let u='gakkii415';try{u=localStorage.getItem('github-counts-user')||u;const g=Number(localStorage.getItem('github-counts-goal'));if(Number.isInteger(g)&&g>0&&g<=100000){setGoal(g);setGoalInput(String(g))}}catch{}setName(u);void load(u);const timer=setInterval(()=>setToday(dayKey(new Date())),60000);return()=>clearInterval(timer)},[]);
 const history=days.filter(d=>d.date<=today),count=history.find(d=>d.date===selected)?.count||0,isToday=selected===today,consecutive=today?streak(history,today):0,best=Math.max(0,...history.map(d=>d.count)),last7=today?calendar(history,today,7):[],week=today?calendar(history,shiftDay(today,-offset*7),7):[],tiles=today?calendar(history,today,35):[],pct=Math.min(100,count/goal*100),complete=count>=goal;
 const selectedIndex=history.findIndex(d=>d.date===selected),prev=history[selectedIndex-1]?.count||0;
 return <main><header><a href="/" className="wordmark"><Zap size={20} fill="currentColor"/>COMMIT<span>QUEST</span></a><Button variant="ghost" size="icon" aria-label="アカウントと目標の設定" onClick={()=>setSettings(!settings)}><Settings2 size={19}/></Button></header>
 {settings&&<section className="settings"><form onSubmit={e=>{e.preventDefault();void load(name.trim())}}><label htmlFor="user">GitHubユーザー名</label><div className="formline"><Input id="user" value={name} onChange={e=>setName(e.target.value)} autoCapitalize="none" autoCorrect="off" spellCheck={false} required maxLength={39}/><Button disabled={busy}>表示</Button></div></form><form onSubmit={e=>{e.preventDefault();const g=Number(goalInput);if(Number.isInteger(g)&&g>0&&g<=100000){setGoal(g);try{localStorage.setItem('github-counts-goal',String(g))}catch{}setSettings(false)}}}><label htmlFor="goal">1日の目標（貢献数）</label><div className="formline"><Input id="goal" type="number" inputMode="numeric" min={1} max={100000} step={1} required value={goalInput} onChange={e=>setGoalInput(e.target.value)}/><Button>保存</Button></div></form></section>}
 <div className="player"><span>@{active||name}</span><Button variant="ghost" size="icon" disabled={busy} aria-label="貢献数を更新" onClick={()=>load(active||name)}><RefreshCw size={16} className={busy?'spin':''}/></Button></div>
 {error&&<div role="alert" className="error">{error}<Button variant="ghost" onClick={()=>load(name.trim())}>再試行</Button></div>}
 {busy&&!days.length?<div className="loading" aria-live="polite"><Skeleton className="h-80 w-full"/><p>冒険の記録を読み込み中…</p></div>:!days.length?<div className="empty">アカウントを確認して、記録を読み込んでください。</div>:<>
 <section className={'scorecard '+(complete?'complete':'')}><div className="score-top"><span>{isToday?'TODAY’S QUEST':`DAILY RECORD / ${short(selected)}`}</span><span className="tier">{dailyTier(count)}</span></div><div className="score-stage"><div className="score-orbit" style={{'--fill':`${pct}%`} as React.CSSProperties}><div className="score-core"><span>{isToday?'今日の貢献数':`${short(selected)}（${wd[new Date(selected+'T12:00:00').getDay()]}）`}</span><strong key={selected+count}>{fmt(count)}</strong><span className="score-unit">CONTRIBUTIONS</span></div></div></div><h1>{complete?'クエスト達成！':count>0?(isToday?'いい調子。今日も前へ。':'この日の一歩も、記録に。'):'今日の一歩を、ここに。'}</h1><p className="score-message">{complete?`目標の${Math.round(count/goal*100)}%を達成。${isToday?'今日':'この日'}の積み重ねが記録に。`:count>0?`目標まで、あと${fmt(goal-count)}件。`:'小さな更新も、あなたの冒険の続き。'}</p><div className="goal-line"><span><Zap size={14}/>DAILY GOAL</span><button onClick={()=>setSettings(true)} aria-label="1日の目標を変更">{fmt(count)} / {fmt(goal)} <Settings2 size={13}/></button></div><Progress value={pct} aria-label="1日の目標達成率"/><div className="score-bottom"><span>{count>prev?`前日より +${fmt(count-prev)}`:count===0?'準備はできている':`${fmt(count)}件の積み重ね`}</span>{count>0&&count>=best?<span><Trophy size={13}/>期間内ベスト</span>:<span>{short(selected)}</span>}</div></section>
 <section className="records"><div><Flame size={20}/><span>連続活動</span><strong>{consecutive}<small>日</small></strong></div><div><Trophy size={20}/><span>1日の最高</span><strong>{fmt(best)}<small>件</small></strong></div><div><Zap size={20}/><span>直近7日</span><strong>{fmt(last7.reduce((s,d)=>s+d.count,0))}<small>件</small></strong></div></section>
 <section className="timeline"><div className="section-head"><div><p className="eyebrow">YOUR DAILY JOURNEY</p><h2>毎日の足あと</h2></div><div className="week-nav"><Button variant="ghost" size="icon" disabled={week[0]?.date<=(days[0]?.date||'')} aria-label="前の7日" onClick={()=>setOffset(offset+1)}><ChevronLeft size={20}/></Button><Button variant="ghost" size="icon" disabled={offset===0} aria-label="次の7日" onClick={()=>setOffset(offset-1)}><ChevronRight size={20}/></Button></div></div><div className="range"><span>{week.length?`${short(week[0].date)} — ${short(week[6].date)}`:''}</span>{(!isToday||offset>0)&&<button onClick={()=>{setOffset(0);setSelected(today)}}>今日に戻る</button>}</div><div className="week-chart">{week.map(d=><button key={d.date} className={'day-column '+(selected===d.date?'selected':'')} onClick={()=>setSelected(d.date)} aria-label={`${d.date} 貢献${d.count}件`} aria-pressed={selected===d.date}><strong>{fmt(d.count)}</strong><div className="bar-track"><div style={{height:`${Math.max(d.count?5:0,d.count/Math.max(1,...week.map(v=>v.count))*100)}%`}}/></div><span>{wd[new Date(d.date+'T12:00:00').getDay()]}</span><small>{short(d.date)}</small><i>{d.count>=goal?<Check size={12}/>:d.date===today?'•':''}</i></button>)}</div><p className="hint">日付をタップして、その日の実績を見る</p></section>
 <section className="collection"><div className="section-head"><div><p className="eyebrow">KEEP THE STORY GOING</p><h2>35日分の積み重ね</h2></div><span className="collection-count">{tiles.filter(d=>d.count>0).length}<small> / 35日</small></span></div><div className="tiles">{tiles.map(d=><button key={d.date} className={`tile ${d.count>=goal?'cleared':d.count>0?'started':''} ${d.date===selected?'picked':''}`} onClick={()=>setSelected(d.date)} aria-label={`${d.date} ${d.count}件`} aria-pressed={selected===d.date}><span>{Number(d.date.slice(8))}</span>{d.count>=goal?<Check size={16}/>:<small>{d.count?fmt(d.count):'—'}</small>}</button>)}</div><div className="legend"><span><i/>活動あり</span><span><i/>目標達成</span></div></section>
 </>}
 <footer><p>1貢献 = 1スコア。貢献数は作業時間や成果の質を表すものではありません。</p><p>GitHubで公開表示される記録を使用。最大約1時間の反映待ちがあります。日付はGitHubの記録、今日の判定は端末時刻です。連続活動は今日が0件でも昨日までの連続日数を表示。最高記録は取得した今年・前年の範囲です。チェックは現在の目標で判定します。</p><div><a href="https://github.com/grubersjoe/github-contributions-api" target="_blank" rel="noreferrer">データ提供 <ArrowUpRight size={12}/></a><span>{updated&&`取得 ${updated} · `}v2</span></div></footer></main>
}
