"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Skeleton} from '@/components/ui/skeleton';
import {RefreshCw} from 'lucide-react';
import {dayKey,shiftDay} from '@/lib/activity';
type Day={date:string;count:number;level:number};
export default function Home({publicApi=false}:{publicApi?:boolean}={}){
 const [name,setName]=useState('gakkii415'),[active,setActive]=useState(''),[days,setDays]=useState<Day[]>([]),[selected,setSelected]=useState<Day|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');const scroll=useRef<HTMLDivElement>(null),seq=useRef(0);
 async function load(user:string){if(!/^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,37}[a-zA-Z0-9])?$/.test(user)){setError('ユーザー名を確認してください。');setBusy(false);return}const id=++seq.current;setBusy(true);setError('');try{const url=publicApi?`https://github-contributions-api.jogruber.de/v4/${encodeURIComponent(user)}?y=last`:`/api/contributions?user=${encodeURIComponent(user)}`;const r=await fetch(url,{signal:AbortSignal.timeout(25000)});const data=await r.json();if(!r.ok||!Array.isArray(data.contributions)||!data.contributions.length)throw Error('貢献数を取得できませんでした。');if(data.contributions.some((d:Day)=>!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!Number.isInteger(d.count)||d.count<0||!Number.isInteger(d.level)||d.level<0||d.level>4))throw Error('データを確認できませんでした。');if(id!==seq.current)return;const end=dayKey(new Date()),start=shiftDay(end,-364),list=(data.contributions as Day[]).filter(d=>d.date>=start&&d.date<=end).sort((a,b)=>a.date.localeCompare(b.date));if(!list.length)throw Error('表示できる記録がありません。');setDays(list);setActive(user);setSelected(list[list.length-1]);try{localStorage.setItem('github-counts-user',user)}catch{}}catch(e){if(id===seq.current)setError(e instanceof Error&&e.name==='TimeoutError'?'時間がかかっています。もう一度お試しください。':'貢献数を取得できませんでした。再度お試しください。')}finally{if(id===seq.current)setBusy(false)}}
 useEffect(()=>{let u='gakkii415';try{u=localStorage.getItem('github-counts-user')||u}catch{}setName(u);void load(u)},[]);
 useEffect(()=>{if(scroll.current)scroll.current.scrollLeft=scroll.current.scrollWidth},[days]);
 const first=days[0]?.date,last=days[days.length-1]?.date,map=new Map(days.map(d=>[d.date,d]));const start=first?shiftDay(first,-new Date(first+'T12:00:00').getDay()):'';const cells:(Day|null)[]=[];if(first&&last){for(let date=start;date<=last;date=shiftDay(date,1)){cells.push(date<first?null:map.get(date)||null)}while(cells.length%7)cells.push(null)}
 const weeks=Array.from({length:cells.length/7},(_,i)=>cells.slice(i*7,i*7+7));let prevMonth='';const labels=weeks.map(week=>{const d=week.find(Boolean);if(!d)return '';const m=d.date.slice(0,7);if(m===prevMonth)return '';prevMonth=m;return Number(m.slice(5))+'月'});
 return <main><form onSubmit={e=>{e.preventDefault();void load(name.trim())}}><label htmlFor="user">@</label><Input id="user" aria-label="GitHubユーザー名" value={name} onChange={e=>setName(e.target.value)} autoCapitalize="none" autoCorrect="off" spellCheck={false} required maxLength={39}/><Button variant="ghost" size="icon" type="submit" disabled={busy} aria-label="貢献数を取得・更新"><RefreshCw size={17} className={busy?'spin':''}/></Button></form>
 {error&&<p role="alert" className="error">{error}</p>}
 {busy&&!days.length?<div className="loading"><Skeleton className="h-52 w-full"/><p>読み込み中…</p></div>:days.length>0&&<><h1>直近1年 <strong>{days.reduce((s,d)=>s+d.count,0).toLocaleString('ja-JP')}</strong> 件の貢献</h1><section className="calendar" aria-label={`${active}の貢献カレンダー`}><div className="chart"><div className="weekdays" aria-hidden="true">{['','月','','水','','金',''].map((d,i)=><span key={i}>{d}</span>)}</div><div className="scroll" ref={scroll}><div className="months" aria-hidden="true" style={{gridTemplateColumns:`repeat(${weeks.length},var(--cell))`}}>{labels.map((m,i)=><span key={i}>{m}</span>)}</div><div className="grass" style={{gridTemplateColumns:`repeat(${weeks.length},var(--cell))`}}>{cells.map((d,i)=>d?<button type="button" key={d.date} className={`cell level-${d.level}${selected?.date===d.date?' selected':''}`} aria-label={`${d.date}、${d.count}件の貢献`} aria-pressed={selected?.date===d.date} title={`${d.date}：${d.count}件`} onClick={()=>setSelected(d)}/>:<span key={`empty-${i}`} className="blank"/>)}</div></div></div><div className="legend" aria-label="薄い緑ほど少なく、濃い緑ほど貢献が多い"><span>少</span>{[0,1,2,3,4].map(n=><i key={n} className={`level-${n}`}/>)}<span>多</span></div></section><output aria-live="polite" className="selection">{selected&&<><time dateTime={selected.date}>{new Date(selected.date+'T12:00:00').toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'})}</time><strong>{selected.count.toLocaleString('ja-JP')}<span> 件の貢献</span></strong></>}</output><p className="hint">マスをタップで件数表示 · 横にスワイプで過去へ</p></>}
 <footer><a href="https://github.com/grubersjoe/github-contributions-api" target="_blank" rel="noreferrer">データ提供</a><span>反映に最大約1時間 · v4</span></footer></main>
}
